servers:
  - http:
      host: localhost
      port: 8000
      middlewares:
        - name: log
        # - name: cors
      routes:
        - path: "/api/.+"
          backend:
            url: http://localhost:4242
        - path: "/frontend/*"
          backend:
            url: http://localhost:5173
